package com.qianqian.collect.mapper;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.qianqian.collect.model.MemBrandCollect;
import com.qianqian.collect.model.MemBrandCollectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MemBrandCollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_brand_collect
     *
     * @mbggenerated Tue Apr 29 10:06:49 CST 2014
     */
    int countByExample(MemBrandCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_brand_collect
     *
     * @mbggenerated Tue Apr 29 10:06:49 CST 2014
     */
    int deleteByExample(MemBrandCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_brand_collect
     *
     * @mbggenerated Tue Apr 29 10:06:49 CST 2014
     */
    int deleteByPrimaryKey(Long collectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_brand_collect
     *
     * @mbggenerated Tue Apr 29 10:06:49 CST 2014
     */
    int insert(MemBrandCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_brand_collect
     *
     * @mbggenerated Tue Apr 29 10:06:49 CST 2014
     */
    int insertSelective(MemBrandCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_brand_collect
     *
     * @mbggenerated Tue Apr 29 10:06:49 CST 2014
     */
    List<MemBrandCollect> selectByExample(MemBrandCollectExample example);
    /**
     * 
     *  @Method_Name    : selectByExample
     *  @param example
     *  @param pageBounds 分页参数对象
     *  @return 
     *  @return         : List<MemBrandCollect>
     *  @Creation Date  : 2014年4月29日 上午10:44:17
     *  @version        : v1.00
     *  @Author         : caozhifei 
     *  @Update Date    : 
     *  @Update Author  :
     */
    List<MemBrandCollect> selectByExample(MemBrandCollectExample example,PageBounds pageBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_brand_collect
     *
     * @mbggenerated Tue Apr 29 10:06:49 CST 2014
     */
    MemBrandCollect selectByPrimaryKey(Long collectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_brand_collect
     *
     * @mbggenerated Tue Apr 29 10:06:49 CST 2014
     */
    int updateByExampleSelective(@Param("record") MemBrandCollect record, @Param("example") MemBrandCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_brand_collect
     *
     * @mbggenerated Tue Apr 29 10:06:49 CST 2014
     */
    int updateByExample(@Param("record") MemBrandCollect record, @Param("example") MemBrandCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_brand_collect
     *
     * @mbggenerated Tue Apr 29 10:06:49 CST 2014
     */
    int updateByPrimaryKeySelective(MemBrandCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_brand_collect
     *
     * @mbggenerated Tue Apr 29 10:06:49 CST 2014
     */
    int updateByPrimaryKey(MemBrandCollect record);
}