package com.qianqian.collect.mapper;

import com.github.miemiedev.mybatis.paginator.domain.PageBounds;
import com.qianqian.collect.model.MemCommodityCollect;
import com.qianqian.collect.model.MemCommodityCollectExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface MemCommodityCollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_commodity_collect
     *
     * @mbggenerated Tue Apr 29 10:06:06 CST 2014
     */
    int countByExample(MemCommodityCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_commodity_collect
     *
     * @mbggenerated Tue Apr 29 10:06:06 CST 2014
     */
    int deleteByExample(MemCommodityCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_commodity_collect
     *
     * @mbggenerated Tue Apr 29 10:06:06 CST 2014
     */
    int deleteByPrimaryKey(Long collectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_commodity_collect
     *
     * @mbggenerated Tue Apr 29 10:06:06 CST 2014
     */
    int insert(MemCommodityCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_commodity_collect
     *
     * @mbggenerated Tue Apr 29 10:06:06 CST 2014
     */
    int insertSelective(MemCommodityCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_commodity_collect
     *
     * @mbggenerated Tue Apr 29 10:06:06 CST 2014
     */
    List<MemCommodityCollect> selectByExample(MemCommodityCollectExample example);
    
    /**
     * 根据查询条件进行分页查询
     *  @Method_Name    : selectByExample
     *  @param example
     *  @param pageBounds 分页参数对象
     *  @return 
     *  @return         : List<MemCommodityCollect>
     *  @Creation Date  : 2014年4月29日 上午10:42:12
     *  @version        : v1.00
     *  @Author         : caozhifei 
     *  @Update Date    : 
     *  @Update Author  :
     */
    List<MemCommodityCollect> selectByExample(MemCommodityCollectExample example,PageBounds pageBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_commodity_collect
     *
     * @mbggenerated Tue Apr 29 10:06:06 CST 2014
     */
    MemCommodityCollect selectByPrimaryKey(Long collectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_commodity_collect
     *
     * @mbggenerated Tue Apr 29 10:06:06 CST 2014
     */
    int updateByExampleSelective(@Param("record") MemCommodityCollect record, @Param("example") MemCommodityCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_commodity_collect
     *
     * @mbggenerated Tue Apr 29 10:06:06 CST 2014
     */
    int updateByExample(@Param("record") MemCommodityCollect record, @Param("example") MemCommodityCollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_commodity_collect
     *
     * @mbggenerated Tue Apr 29 10:06:06 CST 2014
     */
    int updateByPrimaryKeySelective(MemCommodityCollect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mem_commodity_collect
     *
     * @mbggenerated Tue Apr 29 10:06:06 CST 2014
     */
    int updateByPrimaryKey(MemCommodityCollect record);
}