package com.qianqian.collect.model;

import java.util.Date;
/**
 * 会员中心我的品牌收藏实体类
 * @Project 	: member.maxtp
 * @Program Name: com.qianqian.user.model.MemBrandCollect.java
 * @ClassName	: MemBrandCollect 
 * @Author 		: caozhifei 
 * @CreateDate  : 2014年4月29日 上午10:10:00
 */
public class MemBrandCollect {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mem_brand_collect.collect_id
     *
     * @mbggenerated Tue Apr 29 10:06:49 CST 2014
     */
    private Long collectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mem_brand_collect.user_id
     *
     * @mbggenerated Tue Apr 29 10:06:49 CST 2014
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mem_brand_collect.brand_id
     *
     * @mbggenerated Tue Apr 29 10:06:49 CST 2014
     */
    private Long brandId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mem_brand_collect.brand_name
     *
     * @mbggenerated Tue Apr 29 10:06:49 CST 2014
     */
    private String brandName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mem_brand_collect.logo_url
     *
     * @mbggenerated Tue Apr 29 10:06:49 CST 2014
     */
    private String logoUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mem_brand_collect.collect_time
     *
     * @mbggenerated Tue Apr 29 10:06:49 CST 2014
     */
    private Date collectTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mem_brand_collect.collect_id
     *
     * @return the value of mem_brand_collect.collect_id
     *
     * @mbggenerated Tue Apr 29 10:06:49 CST 2014
     */
    public Long getCollectId() {
        return collectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mem_brand_collect.collect_id
     *
     * @param collectId the value for mem_brand_collect.collect_id
     *
     * @mbggenerated Tue Apr 29 10:06:49 CST 2014
     */
    public void setCollectId(Long collectId) {
        this.collectId = collectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mem_brand_collect.user_id
     *
     * @return the value of mem_brand_collect.user_id
     *
     * @mbggenerated Tue Apr 29 10:06:49 CST 2014
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mem_brand_collect.user_id
     *
     * @param userId the value for mem_brand_collect.user_id
     *
     * @mbggenerated Tue Apr 29 10:06:49 CST 2014
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mem_brand_collect.brand_id
     *
     * @return the value of mem_brand_collect.brand_id
     *
     * @mbggenerated Tue Apr 29 10:06:49 CST 2014
     */
    public Long getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mem_brand_collect.brand_id
     *
     * @param brandId the value for mem_brand_collect.brand_id
     *
     * @mbggenerated Tue Apr 29 10:06:49 CST 2014
     */
    public void setBrandId(Long brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mem_brand_collect.brand_name
     *
     * @return the value of mem_brand_collect.brand_name
     *
     * @mbggenerated Tue Apr 29 10:06:49 CST 2014
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mem_brand_collect.brand_name
     *
     * @param brandName the value for mem_brand_collect.brand_name
     *
     * @mbggenerated Tue Apr 29 10:06:49 CST 2014
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mem_brand_collect.logo_url
     *
     * @return the value of mem_brand_collect.logo_url
     *
     * @mbggenerated Tue Apr 29 10:06:49 CST 2014
     */
    public String getLogoUrl() {
        return logoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mem_brand_collect.logo_url
     *
     * @param logoUrl the value for mem_brand_collect.logo_url
     *
     * @mbggenerated Tue Apr 29 10:06:49 CST 2014
     */
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mem_brand_collect.collect_time
     *
     * @return the value of mem_brand_collect.collect_time
     *
     * @mbggenerated Tue Apr 29 10:06:49 CST 2014
     */
    public Date getCollectTime() {
        return collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mem_brand_collect.collect_time
     *
     * @param collectTime the value for mem_brand_collect.collect_time
     *
     * @mbggenerated Tue Apr 29 10:06:49 CST 2014
     */
    public void setCollectTime(Date collectTime) {
        this.collectTime = collectTime;
    }
}