package com.qianqian.collect.model;

import java.util.Date;
/**
 * 会员中心我的商品收藏实体类
 * @Project 	: member.maxtp
 * @Program Name: com.qianqian.user.model.MemCommodityCollect.java
 * @ClassName	: MemCommodityCollect 
 * @Author 		: caozhifei 
 * @CreateDate  : 2014年4月29日 上午10:10:40
 */
public class MemCommodityCollect {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mem_commodity_collect.collect_id
     *
     * @mbggenerated Tue Apr 29 10:06:06 CST 2014
     */
    private Long collectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mem_commodity_collect.commodity_id
     *
     * @mbggenerated Tue Apr 29 10:06:06 CST 2014
     */
    private Long commodityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mem_commodity_collect.user_id
     *
     * @mbggenerated Tue Apr 29 10:06:06 CST 2014
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mem_commodity_collect.commodity_name
     *
     * @mbggenerated Tue Apr 29 10:06:06 CST 2014
     */
    private String commodityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mem_commodity_collect.commodity_image
     *
     * @mbggenerated Tue Apr 29 10:06:06 CST 2014
     */
    private String commodityImage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mem_commodity_collect.collect_time
     *
     * @mbggenerated Tue Apr 29 10:06:06 CST 2014
     */
    private Date collectTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mem_commodity_collect.collect_id
     *
     * @return the value of mem_commodity_collect.collect_id
     *
     * @mbggenerated Tue Apr 29 10:06:06 CST 2014
     */
    public Long getCollectId() {
        return collectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mem_commodity_collect.collect_id
     *
     * @param collectId the value for mem_commodity_collect.collect_id
     *
     * @mbggenerated Tue Apr 29 10:06:06 CST 2014
     */
    public void setCollectId(Long collectId) {
        this.collectId = collectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mem_commodity_collect.commodity_id
     *
     * @return the value of mem_commodity_collect.commodity_id
     *
     * @mbggenerated Tue Apr 29 10:06:06 CST 2014
     */
    public Long getCommodityId() {
        return commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mem_commodity_collect.commodity_id
     *
     * @param commodityId the value for mem_commodity_collect.commodity_id
     *
     * @mbggenerated Tue Apr 29 10:06:06 CST 2014
     */
    public void setCommodityId(Long commodityId) {
        this.commodityId = commodityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mem_commodity_collect.user_id
     *
     * @return the value of mem_commodity_collect.user_id
     *
     * @mbggenerated Tue Apr 29 10:06:06 CST 2014
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mem_commodity_collect.user_id
     *
     * @param userId the value for mem_commodity_collect.user_id
     *
     * @mbggenerated Tue Apr 29 10:06:06 CST 2014
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mem_commodity_collect.commodity_name
     *
     * @return the value of mem_commodity_collect.commodity_name
     *
     * @mbggenerated Tue Apr 29 10:06:06 CST 2014
     */
    public String getCommodityName() {
        return commodityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mem_commodity_collect.commodity_name
     *
     * @param commodityName the value for mem_commodity_collect.commodity_name
     *
     * @mbggenerated Tue Apr 29 10:06:06 CST 2014
     */
    public void setCommodityName(String commodityName) {
        this.commodityName = commodityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mem_commodity_collect.commodity_image
     *
     * @return the value of mem_commodity_collect.commodity_image
     *
     * @mbggenerated Tue Apr 29 10:06:06 CST 2014
     */
    public String getCommodityImage() {
        return commodityImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mem_commodity_collect.commodity_image
     *
     * @param commodityImage the value for mem_commodity_collect.commodity_image
     *
     * @mbggenerated Tue Apr 29 10:06:06 CST 2014
     */
    public void setCommodityImage(String commodityImage) {
        this.commodityImage = commodityImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mem_commodity_collect.collect_time
     *
     * @return the value of mem_commodity_collect.collect_time
     *
     * @mbggenerated Tue Apr 29 10:06:06 CST 2014
     */
    public Date getCollectTime() {
        return collectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mem_commodity_collect.collect_time
     *
     * @param collectTime the value for mem_commodity_collect.collect_time
     *
     * @mbggenerated Tue Apr 29 10:06:06 CST 2014
     */
    public void setCollectTime(Date collectTime) {
        this.collectTime = collectTime;
    }

	@Override
	public String toString() {
		return "MemCommodityCollect [collectId=" + collectId + ", commodityId="
				+ commodityId + ", userId=" + userId + ", commodityName="
				+ commodityName + ", commodityImage=" + commodityImage
				+ ", collectTime=" + collectTime + "]";
	}
    
}